name: Rust

on: [push, pull_request]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 16.0
    - name: llvm-config
      run: llvm-config --version --bindir --libdir
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
